services:
  runner:
    build: .
    container_name: trading-checklist-runner
    env_file:
      - .env
    # mount project so you can edit and keep logs/state external
    volumes:
      - ./:/app:rw
    entrypoint: /bin/sh -c "dos2unix /app/scripts/entrypoint.sh && /app/scripts/entrypoint.sh"
    environment:
      PYTHONUNBUFFERED: "1"
      WEB_MODE: "false"
    # logs to console
    tty: true

  web:
    build: .
    container_name: trading-checklist-web
    env_file:
      - .env
    volumes:
      - ./:/app:rw
    ports:
      - "${WEB_PORT:-5000}:5000"
    entrypoint: /bin/sh -c "dos2unix /app/scripts/entrypoint.sh && /app/scripts/entrypoint.sh"
    environment:
      PYTHONUNBUFFERED: "1"
      WEB_MODE: "true"
    restart: unless-stopped