name: Trigger auto deployment for ezmoney

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ezmoney-AutoDeployTrigger-ceb4a9be-fec3-444c-991a-f01e4f63bcd2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.EZMONEY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EZMONEY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EZMONEY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ezmonewy.azurecr.io
          registryUsername: ${{ secrets.EZMONEY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EZMONEY_REGISTRY_PASSWORD }}
          containerAppName: ezmoney
          resourceGroup: DefaultResourceGroup-SEA
          imageToBuild: ezmonewy.azurecr.io/ezmoney:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


